version: 1.0.{build}
branches:
  only:
  - master
environment:
  DEPLOY_DIR: deploy
  access_token:
    secure: H8F1UMqC4QixM9NbnHewuineXTu860e3WhkpgMzui6xQmCv2qyXd4BDonVrrW5Iv
image: Visual Studio 2013
configuration: Release
platform:
- Win32
- x64
install:
- ps: choco install doxygen.portable
build:
  project: Barst.sln
  verbosity: normal
after_build:
- ps: >-
    mkdir $env:DEPLOY_DIR
    if ($env:PLATFORM -eq "x64") {
        move "$env:APPVEYOR_BUILD_FOLDER\x64\Release\Barst.exe" "$env:DEPLOY_DIR\barst64.exe"
    } else {
        move "$env:APPVEYOR_BUILD_FOLDER\Release\Barst.exe" "$env:DEPLOY_DIR\barst.exe"
    }
artifacts:
- path: $(DEPLOY_DIR)\barst*.exe
  name: barst
on_success:
- ps: >-
    function Check-Error

    {
      param([int]$SuccessVal = 0)
      if ($SuccessVal -ne $LastExitCode) {
        throw "Failed with exit code $LastExitCode"
      }
    }


    if ($env:PLATFORM -eq "x64" -and $env:APPVEYOR_REPO_BRANCH -eq "master" -and -not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      cd "$env:APPVEYOR_BUILD_FOLDER"
      doxygen ./docs/Doxyfile
      mkdir "C:\docs_temp"
      Copy-Item "docs\build\html\*" "C:\docs_temp" -recurse
      Check-Error
      git config --global credential.helper store
      Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
      git config --global user.email "moiein2000@gmail.com"
      git config --global user.name "Matthew Einhorn"
      Check-Error
      git checkout --orphan gh-pages
      Check-Error
      git rm -rf .
      Remove-Item -recurse * -exclude .git
      Copy-Item "C:\docs_temp\*" .  -recurse
      echo "" > .nojekyll
      git add .
      Check-Error
      git commit -a -m "Docs for git-$env:APPVEYOR_REPO_COMMIT"
      Check-Error
      git push origin gh-pages -f
      Check-Error
    }